import { DEFAULTS } from '../config.js';

const EVENT_PLACEHOLDERS = [
  'titel',
  'tag_relativ',
  'tag_relativ_ende',
  'tagesbereich_relativ',
  'datum',
  'datum_kurz',
  'datum_ohne_wochentag',
  'datum_mit_wochentag',
  'datum_mit_wochentag_kurz',
  'datum_ende',
  'datum_ende_kurz',
  'datum_ende_ohne_wochentag',
  'datum_ende_mit_wochentag',
  'datum_ende_mit_wochentag_kurz',
  'datum_relativ',
  'datum_relativ_ende',
  'datumsbereich',
  'datumsbereich_mit_wochentag',
  'datumsbereich_mit_wochentag_kurz',
  'termin_datum',
  'termin_zeit',
  'termin_zeitraum',
  'wochentag',
  'wochentag_kurz',
  'wochentag_ende',
  'wochentag_ende_kurz',
  'uhrzeit',
  'uhrzeit_ende',
  'ort',
];

const REMINDER_PLACEHOLDERS = [...EVENT_PLACEHOLDERS, 'vorlauf', 'vorlauf_kurz'];

const PLACEHOLDER_CATALOG = [
  {
    name: 'Termin',
    placeholders: [
      { key: 'titel', example: 'Elternabend Klasse 4b', description: 'Titel des Termins, ggf. ohne konfiguriertes Präfix.' },
      { key: 'ort', example: 'Aula der Grundschule', description: 'Ort aus dem Kalender oder der konfigurierte Ort-Fallback.' },
    ],
  },
  {
    name: 'Relative Tage',
    placeholders: [
      { key: 'tag_relativ', example: 'Morgen', description: 'Starttag relativ zum Laufzeitpunkt.' },
      { key: 'tag_relativ_ende', example: 'Übermorgen', description: 'Endtag relativ zum Laufzeitpunkt.' },
      { key: 'tagesbereich_relativ', example: 'Morgen bis Übermorgen', description: 'Relativer Tagesbereich; bei eintägigen Terminen nur ein Tag.' },
      { key: 'datum_relativ', example: 'Morgen, So., 20.09.2026', description: 'Relativer Starttag plus Datum.' },
      { key: 'datum_relativ_ende', example: 'Übermorgen, Mo., 21.09.2026', description: 'Relativer Endtag plus Enddatum.' },
    ],
  },
  {
    name: 'Datum & Zeitraum',
    placeholders: [
      { key: 'datum', example: 'So., 20.09.2026', description: 'Rückwärtskompatibles Startdatum mit kurzem Wochentag.' },
      { key: 'datum_kurz', example: '20.09.2026', description: 'Startdatum ohne Wochentag.' },
      { key: 'datum_ohne_wochentag', example: '20.09.2026', description: 'Startdatum ohne Wochentag; Alias für datum_kurz.' },
      { key: 'datum_mit_wochentag', example: 'Sonntag, 20.09.2026', description: 'Startdatum mit ausgeschriebenem Wochentag.' },
      { key: 'datum_mit_wochentag_kurz', example: 'So., 20.09.2026', description: 'Startdatum mit abgekürztem Wochentag.' },
      { key: 'datum_ende', example: 'Di., 22.09.2026', description: 'Rückwärtskompatibles Enddatum mit kurzem Wochentag.' },
      { key: 'datum_ende_kurz', example: '22.09.2026', description: 'Enddatum ohne Wochentag.' },
      { key: 'datum_ende_ohne_wochentag', example: '22.09.2026', description: 'Enddatum ohne Wochentag; Alias für datum_ende_kurz.' },
      { key: 'datum_ende_mit_wochentag', example: 'Dienstag, 22.09.2026', description: 'Enddatum mit ausgeschriebenem Wochentag.' },
      { key: 'datum_ende_mit_wochentag_kurz', example: 'Di., 22.09.2026', description: 'Enddatum mit abgekürztem Wochentag.' },
      { key: 'datumsbereich', example: '20.09.2026–22.09.2026', description: 'Datum oder Datumsbereich ohne relativen Tag und ohne Uhrzeit.' },
      { key: 'datumsbereich_mit_wochentag', example: 'Sonntag, 20.09.2026 – Dienstag, 22.09.2026', description: 'Datumsbereich mit ausgeschriebenen Wochentagen.' },
      { key: 'datumsbereich_mit_wochentag_kurz', example: 'So., 20.09.2026 – Di., 22.09.2026', description: 'Datumsbereich mit kurzen Wochentagen.' },
      { key: 'termin_datum', example: 'Morgen, Sonntag, 20.09.2026', description: 'Älterer kombinierter relativer Datumswert.' },
    ],
  },
  {
    name: 'Wochentage',
    placeholders: [
      { key: 'wochentag', example: 'Sonntag', description: 'Start-Wochentag ausgeschrieben.' },
      { key: 'wochentag_kurz', example: 'So.', description: 'Start-Wochentag abgekürzt.' },
      { key: 'wochentag_ende', example: 'Dienstag', description: 'End-Wochentag ausgeschrieben.' },
      { key: 'wochentag_ende_kurz', example: 'Di.', description: 'End-Wochentag abgekürzt.' },
    ],
  },
  {
    name: 'Uhrzeit',
    placeholders: [
      { key: 'termin_zeit', example: '18:30–20:00 Uhr', description: 'Uhrzeit oder Zeitspanne; leer bei ganztägigen Terminen.' },
      { key: 'termin_zeitraum', example: 'Morgen, Sonntag, 20.09.2026 um 18:30–20:00 Uhr', description: 'Kompletter rückwärtskompatibler Terminzeitraum.' },
      { key: 'uhrzeit', example: '18:30', description: 'Startuhrzeit ohne „Uhr“; leer bei ganztägigen Terminen.' },
      { key: 'uhrzeit_ende', example: '20:00', description: 'Enduhrzeit ohne „Uhr“; leer bei ganztägigen Terminen.' },
    ],
  },
  {
    name: 'Erinnerung',
    placeholders: [
      { key: 'vorlauf', example: '1 Tag', description: 'Vorlaufzeit ausgeschrieben.' },
      { key: 'vorlauf_kurz', example: '1d', description: 'Vorlaufzeit in Kurzschreibweise.' },
    ],
  },
  {
    name: 'Listen',
    placeholders: [
      { key: 'items', example: '• Elternabend…', description: 'Gerenderte Einträge der Sammel- oder Übersichts-Nachricht.' },
      { key: 'anzahl', example: '2', description: 'Anzahl der Termine in der Sammel- oder Übersichts-Nachricht.' },
      { key: 'zeitraum', example: '21.09. – 27.09.2026', description: 'Zeitraum der Wochenübersicht.' },
    ],
  },
];

function placeholderGroups(keys) {
  const allowed = new Set(keys);
  return PLACEHOLDER_CATALOG
    .map((group) => ({
      name: group.name,
      placeholders: group.placeholders.filter((placeholder) => allowed.has(placeholder.key)),
    }))
    .filter((group) => group.placeholders.length > 0);
}

export const SETTINGS = [
  {
    key: 'source',
    env: 'SOURCE',
    group: 'Kalenderquelle',
    label: 'Kalenderquelle',
    type: 'select',
    options: ['file', 'caldav'],
    default: DEFAULTS.source,
    help: '"file" liest eine lokale ICS-Datei; "caldav" liest einen CalDAV-/Nextcloud-Kalender.',
  },
  {
    key: 'icsPath',
    env: 'ICS_PATH',
    group: 'Kalenderquelle',
    label: 'ICS-Datei',
    type: 'path',
    default: DEFAULTS.icsPath,
    help: 'Pfad relativ zum Projektverzeichnis oder absolut.',
  },
  {
    key: 'lookaheadDays',
    env: 'LOOKAHEAD_DAYS',
    group: 'Kalenderquelle',
    label: 'Vorschau-Horizont in Tagen',
    type: 'number',
    default: DEFAULTS.lookaheadDays,
  },
  {
    key: 'caldav.url',
    env: 'CALDAV_URL',
    group: 'CalDAV (optional)',
    label: 'CalDAV-URL',
    type: 'url',
    default: DEFAULTS.caldav.url,
    sensitive: true,
  },
  {
    key: 'caldav.username',
    env: 'CALDAV_USERNAME',
    group: 'CalDAV (optional)',
    label: 'CalDAV-Benutzer',
    type: 'text',
    default: DEFAULTS.caldav.username,
    sensitive: true,
  },
  {
    key: 'caldav.password',
    env: 'CALDAV_PASSWORD',
    group: 'CalDAV (optional)',
    label: 'CalDAV-Passwort',
    type: 'password',
    default: DEFAULTS.caldav.password,
    sensitive: true,
  },
  {
    key: 'caldav.calendar',
    env: 'CALDAV_CALENDAR',
    group: 'CalDAV (optional)',
    label: 'CalDAV-Kalender',
    type: 'text',
    default: DEFAULTS.caldav.calendar,
  },
  {
    key: 'selectByCategory',
    env: 'SELECT_BY_CATEGORY',
    group: 'Terminauswahl',
    label: 'Nach Kategorie filtern',
    type: 'boolean',
    default: DEFAULTS.selectByCategory,
  },
  {
    key: 'selectCategory',
    env: 'SELECT_CATEGORY',
    group: 'Terminauswahl',
    label: 'Kategorie',
    type: 'text',
    default: DEFAULTS.selectCategory,
  },
  {
    key: 'selectByPrefix',
    env: 'SELECT_BY_PREFIX',
    group: 'Terminauswahl',
    label: 'Nach Titel-Präfix filtern',
    type: 'boolean',
    default: DEFAULTS.selectByPrefix,
    help: 'Wenn Kategorie- und Präfixfilter aus sind, zählen alle Kalendertermine als ausgewählt.',
  },
  {
    key: 'selectPrefix',
    env: 'SELECT_PREFIX',
    group: 'Terminauswahl',
    label: 'Titel-Präfix',
    type: 'text',
    default: DEFAULTS.selectPrefix,
  },
  {
    key: 'stripPrefix',
    env: 'STRIP_PREFIX',
    group: 'Terminauswahl',
    label: 'Präfix aus Nachrichten entfernen',
    type: 'boolean',
    default: DEFAULTS.stripPrefix,
  },
  {
    key: 'remindersEnabled',
    env: 'REMINDERS_ENABLED',
    group: 'Erinnerungen',
    label: 'Einzel- und Sammelerinnerungen aktivieren',
    type: 'boolean',
    default: DEFAULTS.remindersEnabled,
    help: 'Unabhängig von der Wochenübersicht. Ausschalten, um ausschließlich Wochenübersichten zu senden.',
  },
  {
    key: 'defaultReminders',
    env: 'DEFAULT_REMINDERS',
    group: 'Erinnerungen',
    label: 'Standard-Vorlaufzeiten',
    type: 'text',
    default: DEFAULTS.defaultReminders,
    help: 'Kommasepariert, z. B. 1d,2h oder 1w,30m.',
  },
  {
    key: 'maxReminders',
    env: 'MAX_REMINDERS',
    group: 'Erinnerungen',
    label: 'Maximale Vorlaufzeiten pro Termin',
    type: 'number',
    default: DEFAULTS.maxReminders,
  },
  {
    key: 'reminderProperty',
    env: 'REMINDER_PROPERTY',
    group: 'Erinnerungen',
    label: 'ICS-Property für Overrides',
    type: 'text',
    default: DEFAULTS.reminderProperty,
  },
  {
    key: 'checkWindowMinutes',
    env: 'CHECK_WINDOW_MINUTES',
    group: 'Erinnerungen',
    label: 'Prüffenster in Minuten',
    type: 'number',
    default: DEFAULTS.checkWindowMinutes,
  },
  {
    key: 'catchUp',
    env: 'CATCH_UP',
    group: 'Erinnerungen',
    label: 'Verpasste Erinnerungen nachholen',
    type: 'boolean',
    default: DEFAULTS.catchUp,
  },
  {
    key: 'timezone',
    env: 'TIMEZONE',
    group: 'Sprache & Darstellung',
    label: 'Zeitzone',
    type: 'text',
    default: DEFAULTS.timezone,
  },
  {
    key: 'locale',
    env: 'LOCALE',
    group: 'Sprache & Darstellung',
    label: 'Locale',
    type: 'text',
    default: DEFAULTS.locale,
  },
  {
    key: 'locationFallback',
    env: 'LOCATION_FALLBACK',
    group: 'Sprache & Darstellung',
    label: 'Ort-Fallback',
    type: 'text',
    default: DEFAULTS.locationFallback,
  },
  {
    key: 'templateSingle',
    env: 'TEMPLATE_SINGLE',
    group: 'Nachrichtentexte',
    label: 'Einzeltermin-Template',
    type: 'template',
    default: DEFAULTS.templateSingle,
    placeholders: REMINDER_PLACEHOLDERS,
    placeholderGroups: placeholderGroups(REMINDER_PLACEHOLDERS),
  },
  {
    key: 'templateCollection',
    env: 'TEMPLATE_COLLECTION',
    group: 'Nachrichtentexte',
    label: 'Sammel-Template',
    type: 'template',
    default: DEFAULTS.templateCollection,
    placeholders: ['items', 'anzahl', 'vorlauf', 'vorlauf_kurz'],
    placeholderGroups: placeholderGroups(['items', 'anzahl', 'vorlauf', 'vorlauf_kurz']),
  },
  {
    key: 'templateCollectionItem',
    env: 'TEMPLATE_COLLECTION_ITEM',
    group: 'Nachrichtentexte',
    label: 'Sammel-Eintrag-Template',
    type: 'template',
    default: DEFAULTS.templateCollectionItem,
    placeholders: REMINDER_PLACEHOLDERS,
    placeholderGroups: placeholderGroups(REMINDER_PLACEHOLDERS),
  },
  {
    key: 'collectionSeparator',
    env: 'COLLECTION_SEPARATOR',
    group: 'Nachrichtentexte',
    label: 'Trenner zwischen Sammel-Einträgen',
    type: 'template',
    default: DEFAULTS.collectionSeparator,
  },
  {
    key: 'digestEnabled',
    env: 'DIGEST_ENABLED',
    group: 'Wochenübersicht',
    label: 'Wochenübersicht aktivieren',
    type: 'boolean',
    default: DEFAULTS.digestEnabled,
  },
  {
    key: 'digestDay',
    env: 'DIGEST_DAY',
    group: 'Wochenübersicht',
    label: 'Versand-Wochentag',
    type: 'text',
    default: DEFAULTS.digestDay,
  },
  {
    key: 'digestTime',
    env: 'DIGEST_TIME',
    group: 'Wochenübersicht',
    label: 'Versand-Uhrzeit',
    type: 'time',
    default: DEFAULTS.digestTime,
  },
  {
    key: 'digestRange',
    env: 'DIGEST_RANGE',
    group: 'Wochenübersicht',
    label: 'Zeitraum der Übersicht',
    type: 'text',
    default: DEFAULTS.digestRange,
    help: 'z. B. 7d, 14d oder next-week.',
  },
  {
    key: 'digestSendWhenEmpty',
    env: 'DIGEST_SEND_WHEN_EMPTY',
    group: 'Wochenübersicht',
    label: 'Leere Übersicht senden',
    type: 'boolean',
    default: DEFAULTS.digestSendWhenEmpty,
  },
  {
    key: 'templateDigest',
    env: 'TEMPLATE_DIGEST',
    group: 'Wochenübersicht',
    label: 'Übersichts-Template',
    type: 'template',
    default: DEFAULTS.templateDigest,
    placeholders: ['items', 'zeitraum', 'anzahl'],
    placeholderGroups: placeholderGroups(['items', 'zeitraum', 'anzahl']),
  },
  {
    key: 'templateDigestItem',
    env: 'TEMPLATE_DIGEST_ITEM',
    group: 'Wochenübersicht',
    label: 'Übersichts-Eintrag-Template',
    type: 'template',
    default: DEFAULTS.templateDigestItem,
    placeholders: EVENT_PLACEHOLDERS,
    placeholderGroups: placeholderGroups(EVENT_PLACEHOLDERS),
  },
  {
    key: 'templateDigestEmpty',
    env: 'TEMPLATE_DIGEST_EMPTY',
    group: 'Wochenübersicht',
    label: 'Leere-Übersicht-Template',
    type: 'template',
    default: DEFAULTS.templateDigestEmpty,
    placeholders: ['zeitraum', 'anzahl'],
    placeholderGroups: placeholderGroups(['zeitraum', 'anzahl']),
  },
  {
    key: 'digestSeparator',
    env: 'DIGEST_SEPARATOR',
    group: 'Wochenübersicht',
    label: 'Trenner zwischen Übersichts-Einträgen',
    type: 'template',
    default: DEFAULTS.digestSeparator,
  },
  {
    key: 'whatsappGroupId',
    env: 'WHATSAPP_GROUP_ID',
    group: 'WhatsApp & Sicherheit',
    label: 'WhatsApp-Gruppen-ID (Legacy)',
    type: 'text',
    default: DEFAULTS.whatsappGroupId,
    help: 'Nur fuer die alte Einzelgruppen-Konfiguration ohne Profile (z. B. reine .env-Nutzung). In Profilen ist die Gruppenliste oben massgeblich; dieses Feld wird dort nicht angezeigt und beim Speichern ignoriert.',
    sensitive: true,
    // In der Profil-GUI ist whatsappTargets[] die alleinige Quelle; dieses Feld bleibt nur fuer
    // rueckwaertskompatible Top-Level-Konfigurationen (kein config.json `profiles`-Array) relevant.
    hidden: true,
  },
  {
    key: 'whatsappPhone',
    env: 'WHATSAPP_PHONE',
    group: 'WhatsApp & Sicherheit',
    label: 'WhatsApp-Telefonnummer (Legacy)',
    type: 'text',
    default: DEFAULTS.whatsappPhone,
    help: 'Nur fuer eine einzelne Person in der Top-Level-Konfiguration ohne Profile. In Profilen ist die Zielliste massgeblich.',
    sensitive: true,
    hidden: true,
  },
  {
    key: 'authDir',
    env: 'AUTH_DIR',
    group: 'WhatsApp & Sicherheit',
    label: 'Session-Ordner',
    type: 'path',
    default: DEFAULTS.authDir,
  },
  {
    key: 'dryRun',
    env: 'DRY_RUN',
    group: 'WhatsApp & Sicherheit',
    label: 'Dry-Run als Standard',
    type: 'boolean',
    default: DEFAULTS.dryRun,
  },
  {
    key: 'recordDryRun',
    env: 'RECORD_DRY_RUN',
    group: 'WhatsApp & Sicherheit',
    label: 'Dry-Runs im State vermerken',
    type: 'boolean',
    default: DEFAULTS.recordDryRun,
  },
  {
    key: 'antibanEnabled',
    env: 'ANTIBAN_ENABLED',
    group: 'WhatsApp & Sicherheit',
    label: 'Konservativen Sendeschutz aktivieren',
    type: 'boolean',
    default: DEFAULTS.antibanEnabled,
    help: 'Begrenzt und verteilt Sendevorgänge zeitlich. Verändert keine Nachrichten und kann eine WhatsApp-Sperre nicht garantieren.',
  },
  {
    key: 'connectTimeoutMs',
    env: 'CONNECT_TIMEOUT_MS',
    group: 'WhatsApp & Sicherheit',
    label: 'Verbindungs-Timeout (ms)',
    type: 'number',
    default: DEFAULTS.connectTimeoutMs,
  },
  {
    key: 'sendDelayMs',
    env: 'SEND_DELAY_MS',
    group: 'WhatsApp & Sicherheit',
    label: 'Minimaler Sendeabstand (ms)',
    type: 'number',
    default: DEFAULTS.sendDelayMs,
  },
  {
    key: 'sendDelayMaxMs',
    env: 'SEND_DELAY_MAX_MS',
    group: 'WhatsApp & Sicherheit',
    label: 'Maximaler Sendeabstand (ms)',
    type: 'number',
    default: DEFAULTS.sendDelayMaxMs,
  },
  {
    key: 'dbPath',
    env: 'DB_PATH',
    group: 'Daten & Logs',
    label: 'SQLite-State-Datei',
    type: 'path',
    default: DEFAULTS.dbPath,
  },
  {
    key: 'pruneAfterDays',
    env: 'PRUNE_AFTER_DAYS',
    group: 'Daten & Logs',
    label: 'State nach Tagen aufräumen',
    type: 'number',
    default: DEFAULTS.pruneAfterDays,
  },
  {
    key: 'logLevel',
    env: 'LOG_LEVEL',
    group: 'Daten & Logs',
    label: 'Log-Level',
    type: 'select',
    options: ['debug', 'info', 'warn', 'error'],
    default: DEFAULTS.logLevel,
  },
];

export const SETTINGS_BY_KEY = new Map(SETTINGS.map((setting) => [setting.key, setting]));

export function groupedSettings() {
  const groups = [];
  const byName = new Map();
  for (const setting of SETTINGS) {
    if (!byName.has(setting.group)) {
      const group = { name: setting.group, settings: [] };
      byName.set(setting.group, group);
      groups.push(group);
    }
    byName.get(setting.group).settings.push(setting);
  }
  return groups;
}
